server:
  port: 5000

telemetry:
  port: 4317
  host: localhost

kafka:
  client:
    clientId: certifications-backend
    brokers:
      - port: 9092
        host: localhost
  consumer:
    groupId: certifications-consumer
    allowAutoTopicCreation: true
